name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has had no activity for over 90 days. It will be closed in 5 days without any futher activity'
        stale-pr-message: 'This PR has had no activity for over 90 days. It will be closed in 5 days without any futher activity'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
        days-before-stale: 90
        days-before-close: 5
